dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: nuboo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: version
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.0
